language: php
php:
  - '7.1'
  - '7.2'
before_script:
  - phpenv config-rm xdebug.ini
cache:
  directories:
    - vendor
    - src/node_modules
before_install:
  - npm install -g npm gulp gulp-cli
install:
  - npm install
script: "Building jobs."
jobs:
  include:
    - stage: build
      if: |
        branch = master OR \
        branch =~ /^release\/.*$/
      script:
        - gulp
    - stage: phplint
      if: |
        branch = master OR \
        branch =~ /^release\/.*$/
      script:
        - composer run-script phpcs
    - stage: deploy
      if: branch =~ /^release\/.*$/
      script: "We made it dora..."
