language: php
php:
  - '7.1'
  - '7.2'
before_script:
  - phpenv config-rm xdebug.ini
cache:
  directories:
    - vendor
    - src/node_modules
script:
  - echo "Testing build process"
  - npm install -g npm gulp gulp-cli
  - npm install
  - gulp
jobs:
  include:
    - stage: phplint
      if: |
        branch = master OR \
        branch =~ /^release\/.*$/
      script:
        - composer install
        - composer run-script phpcs
    - stage: deploy
      if: branch =~ /^release\/.*$/
      script:
        - echo "We made it dora..."
        - npm install -g npm gulp gulp-cli
        - npm install
        - gulp
        - mkdir -p build
        - zip -r bulid/{$TRAVIS_BUILD_NUMBER}.zip . -x@build-excludes.txt
        - ls build/
