language: php
php:
  - '5.6'
  - '7.1'
  - '7.2'
before_script:
  - phpenv config-rm xdebug.ini
cache:
  directories:
    - vendor
    - src/node_modules
before_install:
  - npm install -g npm
  - npm install -g gulp
  - npm install -g gulp-cli
  - composer install
install:
  - cd "src" && npm install
script:
  - gulp
  - cd ../ && composer run-script phpcs