language: php
php:
  - '7.1'
  - '7.2'
env:
  - RELEASE_PREFIX="woominecraft-prerelease-b"
before_script:
  - phpenv config-rm xdebug.ini
cache:
  directories:
    - vendor
    - src/node_modules
script:
  - echo "Testing build process"
  - npm install -g npm gulp gulp-cli
  - npm install
  - gulp
jobs:
  include:
    - stage: phplint
      if: |
        branch = master OR \
        branch =~ /^release\/.*$/
      script:
        - composer install
        - composer run-script phpcs
    - stage: deploy
      if: branch =~ /^release\/.*$/
      script:
        - npm install -g npm gulp gulp-cli
        - npm install
        - gulp
        - gulp build
        - pushd dist
        - ls -alh .
        - tar -cvzf ../$RELEASE_PREFIX$TRAVIS_BUILD_NUMBER.tar.gz ./
        - popd
        - ls -alh ./
      deploy:
        provider: releases
        api_key: $API_KEY
        file: $RELEASE_PREFIX$TRAVIS_BUILD_NUMBER.tar.gz
        skip_cleanup: true
        draft: true
        on:
          all_branches: true
          condition: $TRAVIS_BRANCH =~ ^release\/.*$
