language: php
php:
  - '7.2'
  - '8.0'
before_script:
  - phpenv config-rm xdebug.ini
cache:
  directories:
    - vendor
jobs:
  include:
    - stage: phplint
      if: |
        branch = main OR \
        branch =~ /^release\/.*$/
      script:
        - composer install
        - composer run-script phpcs