version: '2'

services:
  minecraft:
    image: nimmis/spigot
    ports:
      - 25565:25565
    volumes:
      - ./docker/minecraft:/minecraft
      - ./docker/init/mc.yml:/minecraft/plugins/WooMinecraft/config.yml
      - ./docker/WooMinecraft/target/WooMinecraft-1.2.0.jar:/minecraft/plugins/wmc.jar
    environment:
      EULA: 'true'
      SPIGOT_VER: '1.12.2'
      MC_MAXMEM: '2g'
      MC_MINMEM: '512m'

  minecraft2:
    image: nimmis/spigot
    ports:
      - 25566:25565
    volumes:
      - ./docker/minecraft2:/minecraft
      - ./docker/init/mc2.yml:/minecraft/plugins/WooMinecraft/config.yml
      - ./docker/WooMinecraft/target/WooMinecraft-1.2.0.jar:/minecraft/plugins/wmc.jar
    environment:
      EULA: 'true'
      SPIGOT_VER: '1.12.2'
      MC_MAXMEM: '2g'
      MC_MINMEM: '512m'

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - wordpress
    volumes_from:
      - wordpress
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always

  wordpress:
    image: wordpress:5-php7.1-fpm-alpine
    depends_on:
      - mysql
    volumes:
      - ./docker/wordpress:/var/www/html
      - ./src:/var/www/html/wp-content/plugins/woominecraft-wp
      - ./docker/mu-plugins:/var/www/html/wp-content/mu-plugins
      - ./vendor/wp-plugins/woocommerce:/var/www/html/wp-content/plugins/woocommerce
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_PASSWORD: password

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./docker/mysql:/var/lib/mysql
      - ./docker/init/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    ports:
      - 8181:80
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
