version: '2'

services:
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - wordpress
    volumes_from:
      - wordpress
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always

  wordpress:
    build: ./docker/wp
    depends_on:
      - mysql
      - phpmyadmin
    volumes:
      - ./docker/wordpress:/var/www/html
      - ./src:/var/www/html/wp-content/plugins/woominecraft-wp
      - ./docker/mu-plugins:/var/www/html/wp-content/mu-plugins
      - ./vendor/wp-plugins/woocommerce:/var/www/html/wp-content/plugins/woocommerce
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_PASSWORD: password

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    ports:
      - 8181:80
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
